import {readFile,writeFile,mkdir,cp,rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const origin=process.env.SITE_ORIGIN||'https://quqyq-legal.timyname.chatgpt.site';
const words=Object.fromEntries(await Promise.all(['ru','kk'].map(async lang=>[lang,JSON.parse(await readFile(path.join(root,lang==='ru'?'content-ru.json':'content-kz.json'),'utf8'))])));
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slugs={accounts:'arest-scheta',withholding:'uderzhaniya',fee:'oplata-chsi',travel:'zapret-vyezd',car:'arest-avto',property:'arest-nedvizhimosti',inaction:'bezdeystvie-chsi',creditor:'vzyskatel',notary:'ispolnitelnaya-nadpis'};
const routes=['',...Object.values(slugs),'chsi','cases','about','faq','contacts','privacy','consent'];
const local=(l,s='')=>`/${l}/${s?s+'/':''}`;
const arrow='<svg viewBox="0 0 24 24" width="22" height="22" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" fill="none" stroke="currentColor" stroke-width="1.7"/></svg>';
const waIcon='<svg viewBox="0 0 24 24" width="21" height="21" aria-hidden="true"><path d="M20 11.5a8.5 8.5 0 0 1-12.8 7.3L3 20l1.2-4.1A8.5 8.5 0 1 1 20 11.5Z" fill="none" stroke="currentColor" stroke-width="1.6"/><path d="M8 7c-2 5 4 9 7 8l1-2-3-1-1 1-2-2 1-1-1-3Z" fill="none" stroke="currentColor" stroke-width="1.2"/></svg>';
const txt=(l,a,b)=>l==='ru'?a:b;
function wa(l,label,cls='button secondary'){return `<a class="${cls}" aria-label="${escape(label||words[l].contact.whatsapp)}" data-event="whatsapp_click" href="https://wa.me/77081019624?text=${encodeURIComponent(words[l].contact.whatsappGreeting)}" target="_blank" rel="noopener noreferrer">${waIcon}<span>${escape(label||words[l].contact.whatsapp)}</span></a>`;}
function header(l,slug){const w=words[l];return `<a class="skip" href="#main">${txt(l,'Перейти к содержимому','Мазмұнға өту')}</a><header class="header"><a class="brand" href="${local(l)}" aria-label="QŪQYQ — ${escape(w.ui.home)}"><strong>QŪQYQ<span class="brand-dot"></span></strong><small>${escape(w.name)}</small></a><nav class="desktop-nav" aria-label="${escape(w.nav.menu)}"><a href="${local(l)}#services">${escape(w.nav.services)}</a><a href="${local(l)}#process">${escape(w.nav.process)}</a><a href="${local(l,'oplata-chsi')}">${escape(w.nav.calculator)}</a></nav><div class="header-end"><nav class="locales" aria-label="${escape(w.nav.language)}"><a data-event="language_switch" href="${local('ru',slug)}" lang="ru" ${l==='ru'?'aria-current="page"':''}>RU</a><a data-event="language_switch" href="${local('kk',slug)}" lang="kk" ${l==='kk'?'aria-current="page"':''}>ҚАЗ</a></nav><a class="header-contact" href="${local(l,'contacts')}">${escape(w.nav.contact)} ${arrow}</a><button class="menu-button" type="button" aria-expanded="false" aria-controls="mobile-menu" aria-label="${escape(w.nav.menu)}"><svg viewBox="0 0 24 24" width="24" height="24" aria-hidden="true"><path d="M3 7h18M3 12h18M3 17h18" stroke="currentColor" stroke-width="1.7"/></svg></button></div><nav id="mobile-menu" hidden aria-label="${escape(w.nav.menu)}">${['services','process','diagnostic'].map(s=>`<a href="${local(l)}#${s}">${escape(w.nav[s])}</a>`).join('')}<a href="${local(l,'oplata-chsi')}">${escape(w.nav.calculator)}</a><a href="${local(l,'contacts')}">${escape(w.nav.contact)}</a></nav></header>`;}
function hero(l){const w=words[l];return `<section class="hero" data-hero><div class="hero-copy"><p class="geo"><span class="status-dot"></span>${escape(w.hero.geography)}</p><h1>${escape(w.hero.title)}<br><span>${escape(w.hero.titleAccent)}</span></h1><p class="hero-description">${escape(w.hero.description)}</p><div class="actions"><a class="button primary" data-event="hero_cta_click" href="#diagnostic">${escape(w.hero.primary)} ${arrow}</a>${wa(l,w.hero.secondary,'hero-wa text-link')}</div><p class="quiet hero-trust">${escape(w.hero.trust)}</p></div><figure class="hero-art"><img src="/assets/papers-1200.webp" srcset="/assets/papers-640.webp 640w, /assets/papers-1200.webp 1200w" sizes="(max-width:760px) 90vw, 48vw" width="1200" height="900" alt="" fetchpriority="high"><figcaption>${txt(l,'Ясность начинается с документов.','Айқындық құжаттардан басталады.')}</figcaption></figure></section><div class="trust-strip">${w.process.items.map(x=>`<div><span class="step-number">${x.number}</span><p>${escape(x.title)}</p></div>`).join('')}</div>`;}
function art(key,cls=''){const sizes=key==='documents'?'(max-width:760px) 92vw, 45vw':'(max-width:390px) 95px, (max-width:760px) 110px, 45vw';return `<picture class="chapter-art ${cls}"><source srcset="/assets/${key}-480.webp 480w, /assets/${key}-960.webp 960w" sizes="${sizes}" type="image/webp"><img src="/assets/${key}-960.webp" width="960" height="960" loading="lazy" decoding="async" alt=""></picture>`;}
function services(l){const w=words[l];const featured=['accounts','travel'];const row=(service)=>`<a class="service-row" href="${local(l,slugs[service.id])}"><h3>${escape(service.title)}</h3><p>${escape(service.description)}</p>${arrow}</a>`;return `<section id="services" class="section"><div class="section-intro" data-reveal="heading"><h2>${escape(w.services.title)}</h2><p>${escape(w.services.description)}</p></div><div class="service-spotlights">${featured.map((id)=>{const service=w.services.items.find(x=>x.id===id);return `<article class="service-spotlight" data-reveal="chapter">${art(id)}<div class="spotlight-copy"><h3><a href="${local(l,slugs[id])}">${escape(service.title)}</a></h3><p>${escape(service.description)}</p><a class="text-link" href="${local(l,slugs[id])}">${escape(w.ui.readMore)} ${arrow}</a></div></article>`;}).join('')}</div><div class="service-list">${w.services.items.filter(x=>['withholding','fee','inaction'].includes(x.id)).map(row).join('')}</div><details class="more-services"><summary>${txt(l,'Другие ситуации','Басқа жағдайлар')}<span>${txt(l,'Авто, недвижимость, взыскатель, нотариус','Көлік, мүлік, өндіріп алушы, нотариус')}</span>${arrow}</summary><div class="service-list">${w.services.items.filter(x=>!['accounts','travel','withholding','fee','inaction'].includes(x.id)).map(row).join('')}</div></details></section>`;}
function diagnostic(l){const w=words[l];return `<section id="diagnostic" class="diagnostic section" data-reveal="diagnostic"><div class="diagnostic-intro"><h2>${escape(w.diagnostic.title)}</h2><p>${escape(w.diagnostic.description)}</p><p class="privacy-small">${escape(w.diagnostic.privacyNote)}</p><svg class="flow-line" viewBox="0 0 320 100" role="img" aria-label="${txt(l,'От фактов к следующим шагам','Фактілерден келесі қадамдарға')}"><path d="M10 50h100c40 0 30-35 70-35h130M110 50c40 0 30 35 70 35h130" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="10" cy="50" r="5" fill="currentColor"/><circle cx="310" cy="15" r="5" fill="currentColor"/><circle cx="310" cy="85" r="5" fill="currentColor"/></svg></div><div class="wizard" aria-live="polite"><noscript><p>${txt(l,'Для анкеты включите JavaScript. Или обсудите обращение по телефону.','Сауалнама үшін JavaScript қосыңыз немесе телефон арқылы хабарласыңыз.')}</p></noscript><div id="wizard-content"><p>${txt(l,'Анкета загружается…','Сауалнама жүктелуде…')}</p></div></div></section>`;}
function calculator(l){const w=words[l];return `<section id="calculator" class="section calculator" data-reveal="calculator"><div class="calculator-copy"><h2>${escape(w.calculator.title)}</h2><p>${escape(w.calculator.description)}</p><p class="quiet">${escape(w.calculator.disclaimer)}</p><a class="text-link" href="https://adilet.zan.kz/${l==='ru'?'rus':'kaz'}/docs/V2300032907" target="_blank" rel="noopener noreferrer">${escape(w.calculator.source)} · №416 ${arrow}</a><p class="quiet small">${txt(l,'Проверено 05.10.2026. Только денежные требования.','05.10.2026 тексерілді. Тек ақшалай талаптар.')}</p></div><div class="calculator-box"><form id="calculator-form" novalidate><label for="claim-amount">${escape(w.calculator.amountLabel)}</label><div class="money-input"><input id="claim-amount" name="claimAmount" type="text" inputmode="decimal" value="500000" maxlength="18" aria-describedby="amount-note calc-error"><span>₸</span></div><p id="amount-note" class="small quiet">${txt(l,'Денежное требование из документа, не остаток долга.','Құжаттағы ақшалай талап, берешектің қалдығы емес.')}</p><label for="execution-kind">${txt(l,'Условия расчёта','Есептеу шарттары')}</label><select id="execution-kind"><option value="full">${txt(l,'Полное исполнение · МРП 2026 = 4 325 ₸','Толық орындалу · АЕК 2026 = 4 325 ₸')}</option><option value="other">${txt(l,'Частичное исполнение / другое дело / другой год','Ішінара орындалу / өзге іс / басқа жыл')}</option></select><p class="form-error" id="calc-error" role="alert"></p><button class="button primary" type="submit">${escape(w.calculator.calculate)} ${arrow}</button></form><div id="calculator-result" class="calc-result" aria-live="polite"><p class="small">${escape(w.calculator.result)}</p><p class="fee-amount">100 000 ₸</p><p>${escape(w.calculator.rate)}: <strong>20%</strong></p><p class="small quiet">${txt(l,'При полном исполнении требования 500 000 ₸. Не включает расходы.','500 000 ₸ талабы толық орындалғанда. Шығыстар кірмейді.')}</p></div></div></section>`;}
function processSection(l){const w=words[l];return `<section id="process" class="section process"><div class="process-layout"><div class="process-visual"><h2 data-reveal="heading">${escape(w.process.title)}</h2>${art('documents','process-picture')}<p class="process-outcome">${escape(w.process.outcome)}</p></div><div class="process-steps"><div class="process-rail" aria-hidden="true"><span class="process-rail-fill"></span></div><ol class="process-list">${w.process.items.map(x=>`<li data-process-step><span class="process-marker">${x.number}</span><div><h3>${escape(x.title)}</h3><p>${escape(x.description)}</p></div></li>`).join('')}</ol></div></div></section>`;}
function example(l){return `<section class="section example" data-reveal="example"><div><p class="example-label">${txt(l,'Учебный пример · не дело клиента','Оқу мысалы · клиенттің ісі емес')}</p><h2>${txt(l,'Долг погашен.<br>Ограничение осталось.','Берешек өтелді.<br>Шектеу сақталды.')}</h2><p>${txt(l,'Что проверить прежде, чем требовать снятия меры?','Шектеуді алып тастауды сұрамас бұрын нені тексеру керек?')}</p><a class="text-link" data-event="case_open" href="${local(l,'cases')}">${txt(l,'Посмотреть ход разбора','Талдау барысын көру')} ${arrow}</a></div><ol class="example-list"><li>${txt(l,'Сопоставить платёж и сумму требования','Төлем мен талап сомасын салыстыру')}</li><li>${txt(l,'Установить основание окончания производства','Іс жүргізуді аяқтау негізін анықтау')}</li><li>${txt(l,'Проверить другие дела, оплату ЧСИ и расходы','Өзге істерді, ЖСО ақысын және шығыстарды тексеру')}</li><li>${txt(l,'Выбрать обращение по актуальному порядку','Қолданыстағы тәртіппен өтінішті таңдау')}</li></ol></section>`;}
function about(l){const w=words[l];return `<section id="about" class="section about" data-reveal="about"><div class="about-monogram" aria-hidden="true">Т<span>.</span></div><div><h2>${escape(w.about.title)}</h2><p>${escape(w.about.description)}</p><ul class="principles">${w.about.principles.map(x=>`<li>${escape(x)}</li>`).join('')}</ul><p class="quiet">${escape(w.about.geography)}</p><a class="text-link" href="${local(l,'about')}">${escape(w.ui.readMore)} ${arrow}</a></div></section>`;}
function faq(l){const w=words[l];return `<section id="faq" class="section faq"><div><h2>${escape(w.faq.title)}</h2><p class="quiet">${escape(w.ui.legalNote)}</p></div><div class="faq-list">${w.faq.items.map((q,i)=>`<details data-faq="${i}"><summary>${escape(q.question)}<span class="faq-plus" aria-hidden="true">+</span></summary><p>${escape(q.answer)}</p></details>`).join('')}</div></section>`;}
function contact(l,form=true){const w=words[l];return `<section id="contact" class="section contact"><div class="contact-copy"><h2>${escape(w.contact.title)}</h2><p>${escape(w.contact.description)}</p><a class="contact-phone" data-event="phone_click" href="tel:+77081019624">${escape(w.phone)}</a><div class="actions">${wa(l)}<a class="text-link" href="tel:+77081019624" data-event="phone_click">${escape(w.contact.call)} ${arrow}</a></div><p class="quiet small">${txt(l,'WhatsApp — внешний сервис. Документы заранее не отправляйте.','WhatsApp — сыртқы сервис. Құжаттарды алдын ала жібермеңіз.')}</p></div>${form?`<div class="local-form"><h3>${txt(l,'Подготовить обращение','Өтінішті дайындау')}</h3><p class="small quiet">${escape(w.contact.note)}</p><form id="lead-form"><div class="form-grid"><div><label for="lead-name">${escape(w.contact.nameLabel)}</label><input id="lead-name" name="name" autocomplete="given-name" maxlength="60" placeholder="${escape(w.contact.namePlaceholder)}" required></div><div><label for="lead-phone">${escape(w.contact.phoneLabel)}</label><input id="lead-phone" name="phone" type="tel" inputmode="tel" autocomplete="tel" maxlength="25" placeholder="+7 …" pattern="[+0-9 ()−\\-]{7,25}" required></div></div><label for="lead-city">${txt(l,'Город','Қала')}</label><input id="lead-city" name="city" autocomplete="address-level2" maxlength="60" placeholder="${txt(l,'Караганда','Қарағанды')}" required><label for="lead-topic">${txt(l,'Тема обращения','Өтініш тақырыбы')}</label><select id="lead-topic" name="topic">${w.services.items.map(s=>`<option value="${s.id}">${escape(s.title)}</option>`).join('')}</select><label for="lead-message">${escape(w.contact.situationLabel)}</label><textarea id="lead-message" name="message" rows="3" maxlength="500" placeholder="${escape(w.contact.situationPlaceholder)}"></textarea><label class="consent-row"><input type="checkbox" name="consent" required><span>${escape(w.contact.consent)} <a href="${local(l,'privacy')}">${escape(w.contact.privacy)}</a></span></label><button type="submit" class="button primary">${escape(w.contact.submit)} ${arrow}</button></form><div id="prepared-message" hidden><label for="message-preview">${txt(l,'Подготовленный текст','Дайын мәтін')}</label><textarea id="message-preview" rows="6" readonly></textarea><div class="actions"><button type="button" class="button secondary" id="copy-message">${escape(w.contact.copy)}</button>${wa(l)}</div><p id="copy-status" class="small" role="status"></p></div></div>`:''}</section>`;}
function footer(l){const w=words[l];return `<footer class="footer"><div class="footer-top"><a class="brand" href="${local(l)}"><strong>QŪQYQ<span class="brand-dot"></span></strong><small>${escape(w.footer.geography)}</small></a><p>${escape(w.footer.disclaimer)}</p><a class="text-link" href="#top">${escape(w.footer.top)} ${arrow}</a></div><div class="footer-bottom"><span>© 2026 ${escape(w.footer.copyright)} <a href="tel:+77081019624">+7 708 101 96 24</a></span><div><a href="${local(l,'privacy')}">${escape(w.footer.privacy)}</a><a href="${local(l,'consent')}">${txt(l,'Правила обращения','Өтініш ережелері')}</a><a href="https://adilet.zan.kz/" target="_blank" rel="noopener noreferrer">Әділет</a></div></div></footer><div class="mobile-cta" data-mobile-cta><a class="button primary" href="${local(l)}#diagnostic">${escape(w.hero.primary)} ${arrow}</a>${wa(l,w.contact.whatsapp,'mobile-wa')}</div>`;}
const guidance={
accounts:{ru:['Постановление об аресте, уведомление банка и документ — основание взыскания.','Сумма ареста, все действующие производства и назначение поступлений.','Для защищаемых выплат — документы о происхождении денег и типе счёта.'],kk:['Тыйым салу туралы қаулы, банк хабарламасы және өндіріп алу негізі.','Тыйым сомасы, барлық іс жүргізулер және түсімдердің мақсаты.','Қорғалатын төлемдер үшін — ақшаның шығу тегі мен шот түрін растайтын құжаттар.']},
withholding:{ru:['Расчёт работодателя или банка, постановление и вид дохода.','Удержания по всем документам и уже перечисленные суммы.','Правила зависят от характера требования и источника выплаты.'],kk:['Жұмыс беруші не банк есебі, қаулы және кіріс түрі.','Барлық құжаттар бойынша ұсталымдар және аударылған сомалар.','Ережелер талап сипаты мен төлемнің қайдан түскеніне байланысты.']},
fee:{ru:['Постановление об оплате деятельности ЧСИ и денежное требование.','Применимая редакция тарифа, сумма требования и исполненная часть.','Проверить отдельные расходы и основания исключений; калькулятор не устанавливает обязанность платить.'],kk:['ЖСО қызметіне ақы төлеу туралы қаулы және ақшалай талап.','Қолданылатын тариф редакциясы, талап сомасы және орындалған бөлігі.','Бөлек шығыстар мен ерекшеліктерді тексеру; калькулятор төлеу міндетін анықтамайды.']},
travel:{ru:['Постановление о временном ограничении выезда и сведения об извещении.','Основание меры, действующие дела и условия её отмены.','Не покупать поездку в расчёте на обещанное срочное снятие: проверить фактический статус.'],kk:['Шығуды уақытша шектеу туралы қаулы және хабарлау мәліметтері.','Шараның негізі, қолданыстағы істер және жою шарттары.','Жедел алып тастау уәдесіне сүйенбеңіз: нақты мәртебені тексеріңіз.']},
car:{ru:['Постановление и сведения о регистрации автомобиля.','Собственник, характер меры и связь имущества с производством.','Запрет регистрации и арест — разные меры; способ обращения зависит от документа.'],kk:['Қаулы және көлікті тіркеу мәліметтері.','Меншік иесі, шараның сипаты және мүліктің іске қатысы.','Тіркеуге шектеу мен тыйым — түрлі шаралар; өтініш тәртібі құжатқа байланысты.']},
property:{ru:['Постановление, сведения о зарегистрированном праве и обременениях.','Доли собственников, основание взыскания и объём меры.','Наличие единственного жилья само по себе не определяет исход: важны категория требования и документы.'],kk:['Қаулы, тіркелген құқық және ауыртпалықтар туралы мәліметтер.','Меншік иелерінің үлестері, өндіріп алу негізі және шара көлемі.','Жалғыз тұрғын үйдің болуы нәтижені өздігінен анықтамайды: талап түрі мен құжаттар маңызды.']},
inaction:{ru:['Обращения к ЧСИ, подтверждения получения, ответы и материалы дела.','Хронология необходимых и фактически выполненных действий.','Жалоба и возможное судебное обращение — по актуальной редакции; универсальный старый порядок не подходит.'],kk:['ЖСО-ға өтініштер, алынғанын растау, жауаптар және іс материалдары.','Қажетті және нақты жасалған әрекеттердің хронологиясы.','Шағым мен ықтимал сотқа жүгіну — қолданыстағы редакция бойынша; ескі жалпы тәртіп жарамайды.']},
creditor:{ru:['Исполнительный документ, сведения о предъявлении и передаче.','Постановления, обращения, ответы и уже принятые меры.','Возврат, утрата и дубликат документа — отдельные вопросы с доказательствами и сроками.'],kk:['Атқарушылық құжат, ұсыну және беру туралы мәліметтер.','Қаулылар, өтініштер, жауаптар және қабылданған шаралар.','Құжатты қайтару, жоғалту және телнұсқа — дәлелдері мен мерзімдері бар бөлек мәселелер.']},
notary:{ru:['Копия исполнительной надписи, договор и сведения об уведомлении.','Основание бесспорности, содержание возражений и даты получения.','Возражение нотариусу и оспаривание действий ЧСИ имеют разные предмет и порядок.'],kk:['Атқарушылық жазба көшірмесі, шарт және хабарлау мәліметтері.','Даусыздық негізі, қарсылық мазмұны және алу күндері.','Нотариусқа қарсылық пен ЖСО әрекетін даулау нысанасы және тәртібі бөлек.']}
};
function titleFor(l,slug){const w=words[l],service=w.services.items.find(s=>slugs[s.id]===slug);return service?.title||({'chsi':txt(l,'Исполнительное производство и ЧСИ','Атқарушылық іс жүргізу және ЖСО'),'cases':txt(l,'Пример разбора ситуации','Жағдайды талдау мысалы'),'about':w.nav.about,'faq':w.nav.faq,'contacts':w.nav.contact,'privacy':w.privacy.title,'consent':txt(l,'Правила обращения','Өтініш ережелері')})[slug]||w.meta.title;}
function page(l,slug){const w=words[l],s=w.services.items.find(x=>slugs[x.id]===slug);const heading=`<div class="page-heading"><nav class="breadcrumbs" aria-label="${txt(l,'Навигационная цепочка','Навигация тізбегі')}"><a href="${local(l)}">${txt(l,'Главная','Басты бет')}</a><span>/</span><span>${escape(titleFor(l,slug))}</span></nav><h1>${escape(titleFor(l,slug))}</h1>${s?`<p>${escape(s.description)}</p>`:''}</div>`;
if(s) return heading+`<section class="section service-detail"><div><h2>${txt(l,'Что нужно сопоставить','Нені салыстыру керек')}</h2><ol class="checklist">${guidance[s.id][l].map(x=>`<li>${escape(x)}</li>`).join('')}</ol><p class="notice">${txt(l,'Сроки обращения могут быть короткими. Сохраните документы и даты получения; порядок и начало срока требуют отдельной проверки.','Жүгіну мерзімдері қысқа болуы мүмкін. Құжаттар мен алу күндерін сақтаңыз; тәртіп пен мерзімнің басталуын бөлек тексеру қажет.')}</p></div><aside class="service-aside"><h3>${txt(l,'Следующий шаг','Келесі қадам')}</h3><p>${txt(l,'Структурируйте ситуацию в короткой анкете. Затем обсудите обращение без отправки конфиденциальных документов.','Жағдайды қысқа сауалнамада құрылымдаңыз. Кейін құпия құжаттарды жібермей өтінішті талқылаңыз.')}</p><a class="button primary" href="${local(l)}#diagnostic">${escape(w.hero.primary)} ${arrow}</a>${wa(l,w.services.cta)}<p class="small quiet">${escape(w.ui.legalNote)}</p></aside></section>`+(s.id==='fee'?calculator(l):'')+`<section class="section source-section"><h2>${txt(l,'Официальные основания','Ресми негіздер')}</h2><p>${txt(l,'Проверяйте редакцию, применимую к дате вашего дела.','Ісіңіздің күніне қолданылатын редакцияны тексеріңіз.')}</p><a class="text-link" href="https://adilet.zan.kz/${l==='ru'?'rus':'kaz'}/docs/Z100000261_" target="_blank" rel="noopener noreferrer">${txt(l,'Закон об исполнительном производстве','Атқарушылық іс жүргізу туралы заң')} ${arrow}</a></section>`+contact(l,false);
if(slug==='privacy')return heading+`<article class="prose section">${w.privacy.paragraphs.map(p=>`<p>${escape(p)}</p>`).join('')}<h2>${txt(l,'Загрузка документов','Құжаттарды жүктеу')}</h2><p>${txt(l,'В этой версии отключена. Безопасный канал, оператор, условия хранения и удаления должны быть согласованы до передачи материалов.','Бұл нұсқада өшірілген. Материалдарды беру алдында қауіпсіз арна, оператор, сақтау және жою шарттары келісілуі тиіс.')}</p><p>${txt(l,'Редакция от 05.10.2026.','05.10.2026 редакциясы.')}</p></article>`;
if(slug==='consent')return heading+`<article class="prose section"><h2>${txt(l,'Как работает обращение','Өтініш қалай жұмыс істейді')}</h2><p>${txt(l,'Подготовка текста — локальная функция браузера. Она не создаёт заявку, договор или обязательство оказать юридическую услугу. Кнопка WhatsApp открывает внешний сервис с общим приветствием; решение отправить сообщение принимаете вы.','Мәтінді дайындау — браузердің жергілікті функциясы. Ол өтінім, шарт немесе заң көмегін көрсету міндетін тудырмайды. WhatsApp түймесі жалпы сәлемдесумен сыртқы сервисті ашады; хабарламаны жіберуді өзіңіз шешесіз.')}</p><h2>${txt(l,'Перед началом работы','Жұмысты бастамас бұрын')}</h2><p>${txt(l,'Согласуются исполнитель, его полномочия, задача, цена, сроки и конфиденциальность. Сайт не обещает гарантированного снятия ареста и не принимает платежи. Общий материал и калькулятор не заменяют индивидуальное заключение.','Орындаушы, оның өкілеттігі, тапсырма, баға, мерзімдер және құпиялық келісіледі. Сайт тыйымды міндетті түрде алып тастауға уәде бермейді және төлем қабылдамайды. Жалпы материал мен калькулятор жеке қорытындыны алмастырмайды.')}</p><h2>${txt(l,'Рассылки','Хабарламалар тарату')}</h2><p>${txt(l,'Маркетинговые рассылки не включены. Обращение не является согласием на рекламные сообщения.','Маркетингтік тарату қосылмаған. Өтініш жарнамалық хабарламаларға келісім болып саналмайды.')}</p><a href="${local(l,'privacy')}">${escape(w.privacy.title)}</a></article>`;
if(slug==='about')return heading+about(l)+`<section class="section prose"><h2>${txt(l,'Информационный проект','Ақпараттық жоба')}</h2><p>${txt(l,'Публично подтверждённые сведения: имя и контакт, предоставленные владельцем проекта. Профессиональный титул, членство в палате, стаж и судебные результаты здесь не заявляются. Возможность и условия дальнейшей работы обсуждаются отдельно.','Жоба иесі берген мәліметтер: аты және байланысы. Бұл бетте кәсіби атақ, палата мүшелігі, еңбек өтілі және сот нәтижелері мәлімделмейді. Кейінгі жұмыстың мүмкіндігі мен шарттары бөлек талқыланады.')}</p></section>`+contact(l,false);
if(slug==='contacts')return heading+contact(l)+`<section class="section prose"><h2>${txt(l,'География','География')}</h2><p>${escape(w.about.geography)}</p><p>${txt(l,'Встреча назначается заранее. Точный адрес согласуется при обращении.','Кездесу алдын ала белгіленеді. Нақты мекенжай хабарласқан кезде келісіледі.')}</p></section>`;
if(slug==='faq')return heading+faq(l)+contact(l,false);
if(slug==='cases')return heading+example(l)+`<article class="section prose"><h2>${txt(l,'Не предполагать результат заранее','Нәтижені алдын ала болжауға болмайды')}</h2><p>${txt(l,'В учебном сценарии есть платёж, но неизвестны основание окончания, действующие производства и оплата ЧСИ. Вывод о незаконности ограничения до проверки этих фактов был бы преждевременным.','Оқу сценарийінде төлем бар, бірақ аяқтау негізі, қолданыстағы істер және ЖСО ақысы белгісіз. Бұл фактілер тексерілмей шектеу заңсыз деген қорытынды жасау ерте.')}</p><h3>${txt(l,'Документы → проверка → следующий шаг','Құжаттар → тексеру → келесі қадам')}</h3><p>${txt(l,'Платёж и постановления сопоставляются с фактическим статусом. Если найдены основания, определяется подходящая процедура обращения. Если их нет, это также должно быть ясно объяснено. Здесь не приводится реальный клиентский результат.','Төлем мен қаулылар нақты мәртебемен салыстырылады. Негіздер табылса, тиісті жүгіну рәсімі анықталады. Негіздер болмаса, бұл да түсіндірілуі тиіс. Нақты клиенттің нәтижесі көрсетілмеген.')}</p></article>`+contact(l,false);
return heading+services(l)+processSection(l)+faq(l)+contact(l,false);
}
function document(l,slug,body,is404=false){const w=words[l],title=is404?txt(l,'Страница не найдена | QŪQYQ','Бет табылмады | QŪQYQ'):slug?`${titleFor(l,slug)} | QŪQYQ`:w.meta.title;const description=slug?(w.services.items.find(s=>slugs[s.id]===slug)?.description||txt(l,`${titleFor(l,slug)} — информация проекта QŪQYQ. Караганда, Казахстан.`,`${titleFor(l,slug)} — QŪQYQ жобасының ақпараты. Қарағанды, Қазақстан.`)):w.meta.description;const canonical=is404?origin+'/404.html':origin+local(l,slug);const schema={'@context':'https://schema.org','@type':'WebSite',name:'QŪQYQ',url:origin,inLanguage:w.locale};
return `<!doctype html><html lang="${l}" id="top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#f6f4ee"><meta name="color-scheme" content="light"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><meta name="robots" content="noindex,nofollow">${is404?'':`<link rel="canonical" href="${canonical}">`}${is404?'':`<link rel="alternate" hreflang="ru-KZ" href="${origin+local('ru',slug)}"><link rel="alternate" hreflang="kk-KZ" href="${origin+local('kk',slug)}"><link rel="alternate" hreflang="x-default" href="${origin+local('ru',slug)}">`}<meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${origin}/assets/papers-1200.webp"><meta property="og:locale" content="${l==='ru'?'ru_RU':'kk_KZ'}"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="/fonts/noto-sans-variable.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script></head><body data-locale="${l}" data-route="${escape(slug)}"><div class="reading-progress" aria-hidden="true"><span></span></div>${header(l,slug)}<main id="main">${body}</main>${footer(l)}<script type="application/json" id="page-content">${JSON.stringify(w).replaceAll('<','\\u003c')}</script><script type="module" src="/app.mjs"></script></body></html>`;
}
await rm(path.join(root,'dist'),{recursive:true,force:true});await mkdir(path.join(root,'dist'),{recursive:true});
await cp(path.join(root,'frontend'),path.join(root,'dist'),{recursive:true});
for(const l of ['ru','kk'])for(const slug of routes){const body=slug?page(l,slug):hero(l)+services(l)+diagnostic(l)+calculator(l)+processSection(l)+example(l)+about(l)+faq(l)+contact(l);const dir=path.join(root,'dist',l,slug);await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'index.html'),document(l,slug,body));}
await writeFile(path.join(root,'dist/index.html'),document('ru','',hero('ru')+services('ru')+diagnostic('ru')+calculator('ru')+processSection('ru')+example('ru')+about('ru')+faq('ru')+contact('ru')));
await writeFile(path.join(root,'dist/404.html'),document('ru','',`<section class="section page-heading"><h1>Страница не найдена</h1><p>Проверьте адрес или вернитесь на главную.</p><a class="button primary" href="/ru/">На главную ${arrow}</a></section>`,true));
await writeFile(path.join(root,'dist/robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
const urls=routes.flatMap(s=>['ru','kk'].map(l=>`${origin}${local(l,s)}`));
await writeFile(path.join(root,'dist/sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(url=>`<url><loc>${url}</loc><lastmod>2026-10-05</lastmod></url>`).join('')}</urlset>`);
await writeFile(path.join(root,'dist/assets/favicon.svg'),'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#244ade"/><path d="M44 44 36 36M42 29a13 13 0 1 1-26 0 13 13 0 0 1 26 0Z" fill="none" stroke="#fff" stroke-width="5"/></svg>');
console.log(JSON.stringify({pages:routes.length*2+2,origin,locales:['ru','kk'],indexing:'disabled pending professional status',output:path.join(root,'dist')}));
