import {readFile,readdir,stat,writeFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const dist=path.resolve('dist');
async function walk(dir){const list=[];for(const entry of await readdir(dir,{withFileTypes:true})){const p=path.join(dir,entry.name);if(entry.isDirectory())list.push(...await walk(p));else list.push(p);}return list;}
const files=await walk(dist);const pages=files.filter(p=>p.endsWith('.html'));let links=0;const titles=new Map();
for(const file of pages){const html=await readFile(file,'utf8');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(new Set(ids).size,ids.length,`Duplicate IDs ${file}`);assert.equal((html.match(/<h1(?:\s|>)/g)||[]).length,1,`H1 ${file}`);assert.match(html,/<html lang="(?:ru|kk)"/);assert.match(html,/<meta name="description" content="[^"]+"/);assert.match(html,/<meta name="robots" content="noindex,nofollow"/);if(!file.endsWith('/404.html'))assert.match(html,/hreflang="kk-KZ"/);if(!file.endsWith('/404.html'))assert.match(html,/href="https:\/\/quqyq-legal\.timyname\.chatgpt\.site\/(?:ru|kk)\//);assert.match(html,/tel:\+77081019624/);assert.doesNotMatch(html,/<script[^>]+src="https?:/);
const title=html.match(/<title>(.*?)<\/title>/s)[1];if(file!==path.join(dist,'index.html')&&!file.endsWith('/404.html')){assert.ok(!titles.has(title),`Duplicate title ${title}`);titles.set(title,file);}
for(const match of html.matchAll(/\b(?:href|src)="([^"]+)"/g)){const url=match[1];if(url.startsWith('https://wa.me/')){const text=new URL(url.replaceAll('&amp;','&')).searchParams.get('text');assert.ok(!/[0-9]{8}|500|ИИН|ЖСН/.test(text),'Sensitive WA prefill');}if(/^(https?:|tel:|data:)/.test(url))continue;const [pathname,hash]=url.split('#');let target=pathname?path.join(dist,decodeURIComponent(pathname)):file;if(pathname&&pathname.endsWith('/'))target=path.join(target,'index.html');assert.ok(files.includes(target),`Broken link ${url} in ${file}`);if(hash){const text=await readFile(target,'utf8');assert.ok(text.includes(`id="${hash}"`),`Missing anchor ${url} in ${file}`);}links++;}}
assert.ok((await readFile(path.join(dist,'robots.txt'),'utf8')).includes('Allow: /'));
const sizes={};for(const p of files.filter(p=>/\.(mjs|css|webp|woff2)$/.test(p)))sizes[path.relative(dist,p)]=(await stat(p)).size;
const report={pages:pages.length,linksChecked:links,uniquePageTitles:titles.size,missingLinks:0,locales:['ru','kk'],indexing:'intentionally disabled',assets:sizes,browserQA:'not available; no browser checks claimed',checkedAt:new Date().toISOString()};await writeFile('docs/STATIC_AUDIT.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
